trigger:
- main 

pool:
  name: bhaweshnew
  demands:
    - agent.name -equals newagent

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.3.9'

- script: terraform -version
  displayName: 'Check Terraform Version'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendAzureRmUseEntraIdForAuthentication: false
    backendServiceArm: 'bhaweshpipeline'
    backendAzureRmOverrideSubscriptionID: '9f199aee-1ad7-464f-bd74-4b88ef990086'
    backendAzureRmStorageAccountName: 'backednstg'
    backendAzureRmContainerName: 'bhawesh-tfstate'
    backendAzureRmKey: 'tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'bhaweshpipeline'
    