# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- none  # No CI trigger; manual or scheduled execution only

pool:
  name: bhaweshnew  # Custom self-hosted agent pool

steps:
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'SPN_Bhawesh'  # Name of the Azure service connection
    backendAzureRmStorageAccountName: 'backednstg'
    workingDirectory: $(Build.SourcesDirectory)
    backendAzureRmContainerName: 'bhawesh-tfstate'
    backendAzureRmKey: 'logs.tfstate'
