trigger:
- main 

pool:
  name: bhaweshnew
  demands:
    - agent.name -equals newagent

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.3.9'

- script: terraform -version
  displayName: 'Check Terraform Version'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/1/s'
    backendServiceArm: 'Subscription 1(7612edd3-0c0f-4529-a4c1-b982bc1fdb9b)'
    backendAzureRmStorageAccountName: 'bhaweshstg'
    backendAzureRmContainerName: 'bhaweshco'
    backendAzureRmKey: 'bhawesh.tfstate'
